Repository berty/go-orbit-db, pull requests merged in 2019-12, with the labels that each got.

#19 chore: removed init() functions for store types and access controllers
  accesscontroller/base/accesscontroller.go
  accesscontroller/base/doc.go
  accesscontroller/ipfs/accesscontroller_ipfs.go
  accesscontroller/orbitdb/accesscontroller_orbitdb.go
  accesscontroller/simple/accesscontroller_simple.go
  accesscontroller/utils/utils.go
  baseorbitdb/doc.go
  baseorbitdb/logger.go
  baseorbitdb/orbitdb.go
  iface/interface.go
  logger.go
  orbitdb.go
  stores/kvstore/keyvalue.go
  stores/stores_types.go
Labels: ⚠ breaking-change, ✅ Approved

#22 fix: copypaste word error
  stores/kvstore/keyvalue.go
Labels: ✅ Approved

#23 feat: Update to go 1.13
  .circleci/config.yml
  README.md
  cache/cacheleveldown/leveldown.go
  go.mod
  go.sum
  internal/buildconstraints/supported.go
  internal/buildconstraints/unsupported.go
  tests/create_open_test.go
  tests/eventlog_test.go
  tests/keyvalue_test.go
  tests/orbit_db_address_test.go
  tests/persistence_test.go
  tests/replicate_automatically_test.go
  tests/replicate_test.go
  tests/replication_status_test.go
  tests/testing.go
  tests/write_permissions_test.go
Labels: 🔍 Ready for Review

#27 feat: automatic semantic releases
  .github/CODEOWNERS
  .github/workflows/release.yml
  .releaserc.js
Labels: 🔍 Ready for Review

#28 chore: extend test timeout
  Makefile
Labels: 🔍 Ready for Review

#26 fix: removed potential race conditions
  events/events.go
  stores/basestore/base_store.go
Labels: dependent, ✅ Approved
