Repository berty/go-orbit-db, pull requests merged in 2020-08, with the labels that each got.

#60 chore: change the protocolID to match the convention
  pubsub/directchannel/channel.go
Labels: chore, ✅ Approved

#67 fix: some minor bugs + improvements
  baseorbitdb/orbitdb.go
  pubsub/directchannel/channel.go
  stores/basestore/base_store.go
  tests/replicate_automatically_test.go
Labels: bug, ✅ Approved

#68 fix: bump go-ipfs-log@v1.2.6
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review
