Repository berty/go-orbit-db, pull requests merged in 2020-07, with the labels that each got.

#45 feat: bump go-ipfs-log & libp2p
  go.mod
  go.sum
Labels: ✅ Approved

#48 fix: direct channel and peer monitor
  baseorbitdb/orbitdb.go
  pubsub/directchannel/channel.go
Labels: bug, ✅ Approved

#49 fix: remove redundant log `polling for peers`
  pubsub/peermonitor/peermonitor.go
Labels: bug, ✅ Approved

#50 feat: use low level libp2p pubsub, old peermonitor refactor
  baseorbitdb/orbitdb.go
  go.mod
  iface/interface.go
  pubsub/directchannel/channel_test.go
  pubsub/event.go
  pubsub/interface.go
  pubsub/oneonone/events.go
  pubsub/peermonitor/doc.go
  pubsub/peermonitor/event.go
  pubsub/peermonitor/interface.go
  pubsub/peermonitor/peermonitor.go
  pubsub/pubsub.go
  pubsub/pubsubcoreapi/doc.go
  pubsub/pubsubcoreapi/pubsub.go
  pubsub/pubsubraw/doc.go
  pubsub/pubsubraw/pubsub.go
  pubsub/subscription.go
  tests/directchannel_test.go
  tests/replicate_test.go
Labels: enhancement, ✅ Approved

#53 chore: switch to GitHub actions
  .circleci/config.yml
  .github/workflows/go.yml
  .github/workflows/release.yml
  README.md
Labels: chore, 🔍 Ready for Review

#55 fix: handle close chan & goroutine cancel in pubsubraw/pubsubcoreapi
  .github/workflows/go.yml
  Makefile
  accesscontroller/interface.go
  accesscontroller/ipfs/accesscontroller_ipfs.go
  accesscontroller/manifest.go
  accesscontroller/orbitdb/accesscontroller_orbitdb.go
  accesscontroller/simple/accesscontroller_simple.go
  accesscontroller/utils/utils.go
  address/address.go
  baseorbitdb/orbitdb.go
  cache/cacheleveldown/leveldown.go
  cache/interface.go
  go.mod
  go.sum
  iface/interface.go
  orbitdb.go
  pubsub/pubsubcoreapi/pubsub.go
  pubsub/pubsubraw/pubsub.go
  stores/basestore/base_store.go
  stores/basestore/utils.go
  stores/eventlogstore/index.go
  stores/eventlogstore/log.go
  stores/events.go
  stores/operation/operation.go
  stores/replicator/events.go
  stores/replicator/interface.go
  stores/replicator/replicator.go
  tests/create_open_test.go
  tests/eventlog_test.go
  tests/persistence_test.go
  tests/replicate_test.go
  utils/create_db_manifest.go
Labels: bug, 🔍 Ready for Review

#52 WIP: fix: CI
  .github/workflows/go.yml
  Makefile
  accesscontroller/interface.go
  accesscontroller/ipfs/accesscontroller_ipfs.go
  accesscontroller/manifest.go
  accesscontroller/orbitdb/accesscontroller_orbitdb.go
  accesscontroller/simple/accesscontroller_simple.go
  accesscontroller/utils/utils.go
  address/address.go
  baseorbitdb/orbitdb.go
  cache/cacheleveldown/leveldown.go
  cache/interface.go
  iface/interface.go
  orbitdb.go
  stores/basestore/base_store.go
  stores/basestore/utils.go
  stores/eventlogstore/index.go
  stores/eventlogstore/log.go
  stores/events.go
  stores/operation/operation.go
  stores/replicator/events.go
  stores/replicator/interface.go
  stores/replicator/replicator.go
  tests/create_open_test.go
  tests/eventlog_test.go
  tests/persistence_test.go
  utils/create_db_manifest.go
Labels: WIP, 🚧 WIP

#54 chore: refactor unit tests
  .github/workflows/go.yml
  Makefile
  go.mod
  go.sum
  pubsub/directchannel/channel_test.go
  tests/create_open_test.go
  tests/doc.go
  tests/eventlog_test.go
  tests/keyvalue_test.go
  tests/orbit_db_address_test.go
  tests/persistence_test.go
  tests/replicate_automatically_test.go
  tests/replicate_test.go
  tests/replication_status_test.go
  tests/testing_test.go
  tests/write_permissions_test.go
Labels: chore, 🔍 Ready for Review

#59 fix: bump deps
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#61 fix: update go-orbit-db, revert some ipfs deps
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#62 fix: bump deps
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review
